"""order phone

Revision ID: 30896062c5fe
Revises: d632754e4d72
Create Date: 2026-06-26 11:08:21.605095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30896062c5fe'
down_revision: Union[str, None] = 'd632754e4d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
