"""initial schema

Revision ID: d632754e4d72
Revises: 
Create Date: 2026-06-26 09:45:24.519663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd632754e4d72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('EXTERNAL', 'HOUSE', name='account_type'), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_accounts_type'), 'ledger_accounts', ['type'], unique=False)
    op.create_table('ledger_tx',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SALE', name='tx_type'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_tx_type'), 'ledger_tx', ['type'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.BigInteger(), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('from_account_id', sa.UUID(), nullable=False),
    sa.Column('to_account_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='amount_positive'),
    sa.ForeignKeyConstraint(['from_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_from_account_id'), 'ledger_entries', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_to_account_id'), 'ledger_entries', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_tx_id'), 'ledger_entries', ['tx_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('shadybank_account_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'EMAIL_FAILED', name='order_status'), nullable=False),
    sa.Column('bank_desc', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_item_id'), 'orders', ['item_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_item_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ledger_entries_tx_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_to_account_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_from_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_ledger_tx_type'), table_name='ledger_tx')
    op.drop_table('ledger_tx')
    op.drop_index(op.f('ix_ledger_accounts_type'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
